### PR TITLE
 Added the standardisation function

### PR DESCRIPTION
**Pull request by ashish-hacker**
### Assumptions: 
- Before implementing the function , It is assumed that there is no categorical columns or Null values

### CODE REVIEW

**Review by Ask149 — CHANGES_REQUESTED** [review]
Could you please rename the method to the type of standardization used?

**Comment by ashish-hacker** [comment]
ok.

**Review by Ask149 — APPROVED** [review]
Thank you for your contribution.

**Review by Ask149 — APPROVED** [review]

**Review by ishaanballal21 — APPROVED** [review]

**Comment by Ask149** [comment]
Hi @ashish-hacker, we have approved the PR, however, there are some conflicts in the PR, can you rebase the master branch with your branch and push the changes again.

**Comment by ashish-hacker** [comment]
Hey @Ask149 , Thanks for the PR : )
I didn't created any other branches and did all my commits directly on master branch only. So at this stage I am kinda clueless What is it I have to do. Can you guide me a little further.
That would be helpful.

**Review by Ask149 — DISMISSED** [review]

**Review by Ask149 — APPROVED** [review]

**Pull request merged**
