### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aditi1403**
I have made some minor grammatical edits to the README.md file.

### CODE REVIEW

**Review by Ask149 — APPROVED** [review]
Looks fine

**Review by ishaanballal21 — APPROVED** [review]

**Comment by Ask149** [comment]
Thank you for your contribution.

**Comment by aditi1403** [comment]
@Ask149 Sir can you please add labels to my PR as I am a GSSoC'21 participant.
Thank you

**Comment by Ask149** [comment]
#

> @Ask149 Sir can you please add labels to my PR as I am a GSSoC'21 participant.
> Thank you

@aditi1403 Can you join the slack channel  [`HERE`](https://join.slack.com/t/klareda/shared_invite/zt-ndytbmnq-ARgpyJLPMbeFyYo87jrTjA) to discuss this further?

**Pull request merged**
